---
- name: Mount disk to OpenNebula datastores root
  ansible.posix.mount:
    path: /var/lib/one/datastores
    src: UUID={{ one_datastores_disk_uuid }}
    fstype: ext4
    state: mounted
  when: one_datastores_disk_uuid is defined

- name: Set ownership and permissions for OpenNebula datastores root
  ansible.builtin.file:
    path: /var/lib/one/datastores
    state: directory
    owner: oneadmin
    group: oneadmin
    mode: '0750'

- name: Mount disks to individual OpenNebula datastores
  ansible.posix.mount:
    path: /var/lib/one/datastores/{{ item.id }}
    src: UUID={{ item.disk_uuid }}
    fstype: ext4
    state: mounted
  loop: "{{ one_datastore_mounts }}"
  loop_control:
    label: "{{ item.id }}"

- name: Set ownership and permissions for individual OpenNebula datastores
  ansible.builtin.file:
    path: /var/lib/one/datastores/{{ item.id }}
    state: directory
    owner: oneadmin
    group: oneadmin
    mode: '0755'
  loop: "{{ one_datastore_mounts }}"
  loop_control:
    label: "{{ item.id }}"
