---
- name: Install OpenNebula node software
  ansible.builtin.import_tasks: one-node.yml

- name: Configure networking
  ansible.builtin.import_tasks: networking.yml

- name: Configure disks
  ansible.builtin.import_tasks: disk.yml

- name: Configure passwordless ssh
  ansible.builtin.import_tasks: ssh.yml

- name: Configure OpenNebula host
  ansible.builtin.import_tasks: onehost.yml

- name: Run tasks specific to development clusters
  ansible.builtin.import_tasks: dev-cluster.yml
  when: one_host.type | default(one_host_type) == "development"
