---
- name: Get default libvirt network info
  command:
    cmd: virsh net-info default
  register: result
  ignore_errors: true
  changed_when: false

- name: Stop default libvirt network
  command:
    cmd: virsh net-destroy default
  when: 'result.stdout is search("Active:\s+yes")'

- name: Disable autostart for default libvirt network
  command:
    cmd: virsh net-autostart --network default --disable
  when: 'result.stdout is search("Autostart:\s+yes")'

- name: Add wand Open vSwitch apt signing key
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/wand/openvswitch/gpg.2E801E8CCE233F26.key
    id: "{{ openvswitch_apt_key_fingerprint }}"
    state: present

- name: Add wand Open vSwitch apt repository
  ansible.builtin.apt_repository:
    repo: deb https://dl.cloudsmith.io/public/wand/openvswitch/deb/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    filename: wand-openvswitch
    update_cache: yes
    state: present

- name: Install openvswitch-switch
  apt:
    name: openvswitch-switch
    state: present

- name: Create virtual bridges
  openvswitch_bridge:
    bridge: "{{ item.bridge }}"
    state: present
  loop: "{{ one_host.network_interfaces }}"
  loop_control:
    label: "{{ item.bridge }}"

- name: Add external ports to virtual bridges
  openvswitch_port:
    bridge: "{{ item.bridge }}"
    port: "{{ item.extport }}"
    state: present
  loop: "{{ one_host.network_interfaces }}"
  loop_control:
    label: "{{ item.extport }}"

- name: Configure private network
  include_tasks:
    file: private-net.yml
  when: one_host.private_net is defined
