---
- name: Install LXD
  apt:
    name: lxd
    state: present

- name: Add OpenNebula apt signing key
  apt_key:
    id: "{{ one_apt_key_fingerprint }}"
    url: https://downloads.opennebula.org/repo/repo.key
    state: present

- name: Add OpenNebula {{ one_version }} apt repository
  apt_repository:
    repo: deb https://downloads.opennebula.org/repo/{{ one_version }}/{{ ansible_distribution }}/{{ ansible_distribution_version }} stable opennebula
    filename: opennebula
    update_cache: yes
    state: present

- name: Install opennebula-node-lxd
  apt:
    name: opennebula-node-lxd
    state: present
  notify:
    - restart lxd
    - restart libvirt-bin
