---
- name: Create private network bridge ({{ one_host.private_net.internal.bridge }})
  openvswitch.openvswitch.openvswitch_bridge:
    bridge: "{{ one_host.private_net.internal.bridge }}"
    state: present

- name: Install legacy ebtables
  ansible.builtin.apt:
    name: ebtables
    state: present

- name: Install bridge-utils
  ansible.builtin.apt:
    name: bridge-utils
    state: present

- name: Check for netplan
  ansible.builtin.stat:
    path: /usr/sbin/netplan
  register: check_for_netplan

- name: Configure netplan
  ansible.builtin.template:
    src: one-net/netplan.yaml
    dest: /etc/netplan/20-one-net.yaml
    owner: root
    group: root
    mode: '0644'
  notify: netplan apply
  when: "check_for_netplan.stat.exists"

- name: Configure netplan ifup hook
  ansible.builtin.template:
    src: one-net/netplan-ifup-hook
    dest: /etc/networkd-dispatcher/routable.d/20-one-net-ifup-hook
    owner: root
    group: root
    mode: '0755'
  notify: netplan apply
  when: "check_for_netplan.stat.exists"

- name: Configure ifupdown
  ansible.builtin.template:
    src: one-net/ifupdown
    dest: /etc/network/interfaces.d/one-net
    owner: root
    group: root
    mode: '0644'
  notify: restart networking
  when: "not check_for_netplan.stat.exists"
