---
- name: Create private network bridge (br-private)
  openvswitch_bridge:
    bridge: br-private
    state: present

- name: Create one-net systemd service
  template:
    src: one-net.service
    dest: /etc/systemd/system/one-net.service
    owner: root
    group: root
    mode: '0644'
  notify: systemd daemon-reload

- name: Add one-net script
  template:
    src: one-net
    dest: /usr/local/bin/one-net
    owner: root
    group: root
    mode: '0755'
  notify: restart one-net

- name: Start and enable one-net
  service:
    name: one-net
    state: started
    enabled: yes

- name: Configure netplan
  template:
    src: 20-one-net.yaml
    dest: /etc/netplan/20-one-net.yaml
    owner: root
    group: root
    mode: '0644'
  notify: netplan apply
