---
- name: Set authorized keys
  template:
    src: ssh/authorized_keys
    dest: /var/lib/one/.ssh/authorized_keys
    owner: oneadmin
    group: oneadmin
    mode: u=rw,g=,o=

- name: Add KVM and LXD hostnames for all hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.one_host.ip }} kvm.{{ item.inventory_hostname }} lxd.{{ item.inventory_hostname }}"
    regexp: 'kvm.{{ item.inventory_hostname }}'
    state: present
  with_items: "{{ one_related_hosts }}"
  loop_control:
      label: "{{ item.inventory_hostname }}"

- name: Configure known hosts
  template:
    src: ssh/known_hosts
    dest: /var/lib/one/.ssh/known_hosts
    owner: oneadmin
    group: oneadmin
    mode: u=rw,g=,o=
