---
- name: Set authorized keys
  template:
    src: ssh/authorized_keys
    dest: /var/lib/one/.ssh/authorized_keys
    owner: oneadmin
    group: oneadmin
    mode: u=rw,g=,o=

- name: Configure known hosts
  template:
    src: ssh/known_hosts
    dest: /var/lib/one/.ssh/known_hosts
    owner: oneadmin
    group: oneadmin
    mode: u=rw,g=,o=
