---
- name: restart libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: restarted

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart one-net
  ansible.builtin.service:
    name: one-net
    state: restarted

- name: netplan apply
  ansible.builtin.command:
    cmd: netplan apply

- name: restart networking
  ansible.builtin.service:
    name: networking.service
    state: restarted
