---
- name: restart lxd
  service:
    name: lxd
    state: restarted

- name: restart libvirtd
  service:
    name: libvirtd
    state: restarted

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: restart one-net
  service:
    name: one-net
    state: restarted

- name: netplan apply
  command: netplan apply

- name: restart networking
  service:
    name: networking.service
    state: restarted
