#jinja2: trim_blocks: "false", lstrip_blocks: "true"
# {{ ansible_managed }}

network:
  version: 2
  renderer: networkd
  ethernets:
    {{ one_host.private_net.external.bridge }}:
      {% if one_host.private_net.external.ip is defined %}
      addresses:
        - {{ one_host.private_net.external.ip }}
      {% else %}
      dhcp4: true
      {% endif %}
      routes:
        - to: 0.0.0.0/0
          via: {{ one_host.private_net.external.gateway }}
          table: 101
        - to: {{ one_host.private_net.external.network }}
          scope: link
          table: 101
      optional: false
    {{ one_host.private_net.internal.bridge }}:
      addresses:
        - {{ one_host.private_net.internal.ip }}
      routes:
        - to: {{ one_host.private_net.internal.network }}
          scope: link
          table: 101
      routing-policy:
        - from: {{ one_host.private_net.internal.network }}
          table: 101
      optional: false
  bridges:
    {{ one_host.private_net.bridge }}:
      interfaces:
        - {{ one_host.private_net.external.bridge }}
        - {{ one_host.private_net.internal.bridge }}
      optional: false
