#!/bin/sh
# {{ ansible_managed }}

# Route IPv4 but bridge IPv6
ebtables -t broute -F
ebtables -t broute -A BROUTING -p ipv4 -i br-redcables -j DROP
ebtables -t broute -A BROUTING -p ipv4 -i br-private -j DROP
ebtables -t broute -A BROUTING -p arp -i br-redcables -j DROP
ebtables -t broute -A BROUTING -p arp -i br-private -j DROP

# Make sure firewall rules are loaded for br-redcables and br-private
bearwall2
